# Writes a header with a hash of the shader translator's sources, so shader
# sets exported from runtime translations are only served by a runtime whose
# translator matches the one that made them.
#
# usage: cmake -DOUTPUT=<header> -DINPUTS=<file|file|...> -P translator_hash.cmake

string(REPLACE "|" ";" _inputs "${INPUTS}")
list(SORT _inputs)
set(_hashes "")
foreach(_input IN LISTS _inputs)
  file(SHA256 "${_input}" _file_hash)
  get_filename_component(_name "${_input}" NAME)
  string(APPEND _hashes "${_name}:${_file_hash}\n")
endforeach()
string(SHA256 _hash "${_hashes}")
string(SUBSTRING "${_hash}" 0 16 _hash)

set(_content "#pragma once\n// Generated by cmake/translator_hash.cmake - do not edit.\n#define REX_SHADER_TRANSLATOR_HASH \"${_hash}\"\n")
if(EXISTS "${OUTPUT}")
  file(READ "${OUTPUT}" _existing)
  if(_existing STREQUAL _content)
    return()
  endif()
endif()
file(WRITE "${OUTPUT}" "${_content}")
